// Catálogo central de códigos de erro
// Formato: MODULO_DESCRICAO_DO_ERRO
// Adicionar novos códigos aqui ANTES de usá-los

export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  // Tenant
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_PLAN_LIMIT_REACHED: 'TENANT_PLAN_LIMIT_REACHED',
  TENANT_INACTIVE: 'TENANT_INACTIVE',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',

  // Instances (WhatsApp)
  INSTANCE_NOT_FOUND: 'INSTANCE_NOT_FOUND',
  INSTANCE_NOT_CONNECTED: 'INSTANCE_NOT_CONNECTED',
  INSTANCE_ALREADY_CONNECTED: 'INSTANCE_ALREADY_CONNECTED',
  INSTANCE_LIMIT_REACHED: 'INSTANCE_LIMIT_REACHED',
  INSTANCE_NAME_ALREADY_EXISTS: 'INSTANCE_NAME_ALREADY_EXISTS',
  INSTANCE_EVOLUTION_CREATE_FAILED: 'INSTANCE_EVOLUTION_CREATE_FAILED',
  INSTANCE_EVOLUTION_SYNC_FAILED: 'INSTANCE_EVOLUTION_SYNC_FAILED',

  // Broadcasts
  BROADCAST_EMPTY_LIST: 'BROADCAST_EMPTY_LIST',
  BROADCAST_NOT_FOUND: 'BROADCAST_NOT_FOUND',
  BROADCAST_ALREADY_RUNNING: 'BROADCAST_ALREADY_RUNNING',

  // Contacts
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  CONTACT_DUPLICATE: 'CONTACT_DUPLICATE',

  // Groups
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_MEMBERS_FETCH_FAILED: 'GROUP_MEMBERS_FETCH_FAILED',

  // Assistants
  ASSISTANT_NOT_FOUND: 'ASSISTANT_NOT_FOUND',
  ASSISTANT_AI_ERROR: 'ASSISTANT_AI_ERROR',

  // Inbox
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_ALREADY_ASSIGNED: 'CONVERSATION_ALREADY_ASSIGNED',
  CONVERSATION_NOT_OPEN: 'CONVERSATION_NOT_OPEN',
  CONVERSATION_ALREADY_CLOSED: 'CONVERSATION_ALREADY_CLOSED',
  CONVERSATION_NOT_PENDING: 'CONVERSATION_NOT_PENDING',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',

  // Generic
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
} as const

export type ErrorCode = keyof typeof ERROR_CODES
