// Catálogo central de códigos de erro
// Formato: MODULO_DESCRICAO_DO_ERRO
// Adicionar novos códigos aqui ANTES de usá-los

export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_FORBIDDEN_NOT_SUPER_ADMIN: 'AUTH_FORBIDDEN_NOT_SUPER_ADMIN',
  AUTH_FORBIDDEN_INSUFFICIENT_ROLE: 'AUTH_FORBIDDEN_INSUFFICIENT_ROLE',

  // Tenant
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_PLAN_LIMIT_REACHED: 'TENANT_PLAN_LIMIT_REACHED',
  TENANT_INACTIVE: 'TENANT_INACTIVE',
  TENANT_SLUG_ALREADY_EXISTS: 'TENANT_SLUG_ALREADY_EXISTS',
  TENANT_ADMIN_EMAIL_EXISTS: 'TENANT_ADMIN_EMAIL_EXISTS',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_CANNOT_DELETE_SELF: 'USER_CANNOT_DELETE_SELF',
  USER_LAST_ADMIN: 'USER_LAST_ADMIN',
  USER_LIMIT_REACHED: 'USER_LIMIT_REACHED',

  // Instances (WhatsApp)
  INSTANCE_NOT_FOUND: 'INSTANCE_NOT_FOUND',
  INSTANCE_NOT_CONNECTED: 'INSTANCE_NOT_CONNECTED',
  INSTANCE_ALREADY_CONNECTED: 'INSTANCE_ALREADY_CONNECTED',
  INSTANCE_LIMIT_REACHED: 'INSTANCE_LIMIT_REACHED',
  INSTANCE_NAME_ALREADY_EXISTS: 'INSTANCE_NAME_ALREADY_EXISTS',
  INSTANCE_EVOLUTION_CREATE_FAILED: 'INSTANCE_EVOLUTION_CREATE_FAILED',
  INSTANCE_EVOLUTION_SYNC_FAILED: 'INSTANCE_EVOLUTION_SYNC_FAILED',

  // Broadcasts
  BROADCAST_EMPTY_LIST: 'BROADCAST_EMPTY_LIST',
  BROADCAST_NOT_FOUND: 'BROADCAST_NOT_FOUND',
  BROADCAST_ALREADY_RUNNING: 'BROADCAST_ALREADY_RUNNING',
  BROADCAST_CANNOT_PAUSE: 'BROADCAST_CANNOT_PAUSE',
  BROADCAST_CANNOT_RESUME: 'BROADCAST_CANNOT_RESUME',
  BROADCAST_CANNOT_CANCEL: 'BROADCAST_CANNOT_CANCEL',
  BROADCAST_DAILY_LIMIT: 'BROADCAST_DAILY_LIMIT',
  BROADCAST_CONTACT_LIMIT: 'BROADCAST_CONTACT_LIMIT',
  BROADCAST_NO_CONNECTED_INSTANCE: 'BROADCAST_NO_CONNECTED_INSTANCE',
  BROADCAST_CANNOT_DELETE: 'BROADCAST_CANNOT_DELETE',

  // Contacts
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  CONTACT_DUPLICATE: 'CONTACT_DUPLICATE',

  // Groups
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_MEMBERS_FETCH_FAILED: 'GROUP_MEMBERS_FETCH_FAILED',
  GROUP_EXTRACT_INSTANCE_NOT_CONNECTED: 'GROUP_EXTRACT_INSTANCE_NOT_CONNECTED',
  GROUP_EXTRACT_ALREADY_IN_PROGRESS: 'GROUP_EXTRACT_ALREADY_IN_PROGRESS',
  GROUP_EXTRACT_FAILED: 'GROUP_EXTRACT_FAILED',

  // Contact Lists
  CONTACT_LIST_NOT_FOUND: 'CONTACT_LIST_NOT_FOUND',
  CONTACT_LIST_EMPTY: 'CONTACT_LIST_EMPTY',
  CSV_PARSE_ERROR: 'CSV_PARSE_ERROR',
  CSV_EMPTY: 'CSV_EMPTY',

  // Assistants
  ASSISTANT_NOT_FOUND: 'ASSISTANT_NOT_FOUND',
  ASSISTANT_AI_ERROR: 'ASSISTANT_AI_ERROR',

  // Inbox
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CONVERSATION_ALREADY_ASSIGNED: 'CONVERSATION_ALREADY_ASSIGNED',
  CONVERSATION_NOT_OPEN: 'CONVERSATION_NOT_OPEN',
  CONVERSATION_ALREADY_CLOSED: 'CONVERSATION_ALREADY_CLOSED',
  CONVERSATION_NOT_PENDING: 'CONVERSATION_NOT_PENDING',
  MESSAGE_SEND_FAILED: 'MESSAGE_SEND_FAILED',
  INBOX_QUOTED_MESSAGE_NOT_FOUND: 'INBOX_QUOTED_MESSAGE_NOT_FOUND',
  SYNC_FAILED: 'SYNC_FAILED',
  NOT_A_GROUP: 'NOT_A_GROUP',

  // Media
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MEDIA_NOT_AVAILABLE: 'MEDIA_NOT_AVAILABLE',
  MEDIA_DOWNLOAD_FAILED: 'MEDIA_DOWNLOAD_FAILED',
  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',

  // Storage
  STORAGE_UPLOAD_FAILED: 'STORAGE_UPLOAD_FAILED',

  // Import
  IMPORT_INSTANCE_NOT_CONNECTED: 'IMPORT_INSTANCE_NOT_CONNECTED',
  IMPORT_ALREADY_IN_PROGRESS: 'IMPORT_ALREADY_IN_PROGRESS',
  IMPORT_FETCH_CHATS_FAILED: 'IMPORT_FETCH_CHATS_FAILED',

  // Pipeline
  PIPELINE_NOT_FOUND: 'PIPELINE_NOT_FOUND',
  PIPELINE_IS_DEFAULT: 'PIPELINE_IS_DEFAULT',
  PIPELINE_STAGE_NOT_FOUND: 'PIPELINE_STAGE_NOT_FOUND',
  PIPELINE_STAGE_HAS_DEALS: 'PIPELINE_STAGE_HAS_DEALS',
  PIPELINE_STAGE_IS_DEFAULT: 'PIPELINE_STAGE_IS_DEFAULT',
  PIPELINE_REQUIRES_ACTIVE_STAGE: 'PIPELINE_REQUIRES_ACTIVE_STAGE',
  PIPELINE_REQUIRES_WON_STAGE: 'PIPELINE_REQUIRES_WON_STAGE',
  PIPELINE_REQUIRES_LOST_STAGE: 'PIPELINE_REQUIRES_LOST_STAGE',

  // Deals
  DEAL_NOT_FOUND: 'DEAL_NOT_FOUND',
  DEAL_ALREADY_CLOSED: 'DEAL_ALREADY_CLOSED',
  DEAL_STAGE_INVALID_PIPELINE: 'DEAL_STAGE_INVALID_PIPELINE',
  DEAL_ACTIVE_EXISTS: 'DEAL_ACTIVE_EXISTS',
  DEAL_NOTE_NOT_FOUND: 'DEAL_NOTE_NOT_FOUND',

  // Plans
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PLAN_SLUG_ALREADY_EXISTS: 'PLAN_SLUG_ALREADY_EXISTS',
  PLAN_IS_DEFAULT: 'PLAN_IS_DEFAULT',
  PLAN_HAS_TENANTS: 'PLAN_HAS_TENANTS',

  // Tags
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  TAG_NAME_ALREADY_EXISTS: 'TAG_NAME_ALREADY_EXISTS',

  // Notifications
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // Generic
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
} as const

export type ErrorCode = keyof typeof ERROR_CODES
